# ===== BUILD =====
FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# ===== RUN =====
FROM eclipse-temurin:21-jre
WORKDIR /app
# Copy the Spring Boot repackaged jar (with BOOT-INF) and rename to app.jar
COPY --from=build /app/target/*-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
